export { default as NavigationBar } from './NavigationBar/NavigationBar'
export { default as Home} from './home/home'
export { default as WhatsAppAnalyzer} from './whatsappAnalyzer/WhatsAppAnalyzer'
export { default as SnakeField } from './Snake/SnakeField'
export { default as FractalTree } from './FractalTree/FractalTree'
