export { default as NavigationBar } from './NavigationBar'
export { default as Home} from './home/home'
export { default as WhatsAppAnalyzer} from './whatsappAnalyzer/WhatsAppAnalyzer'
export { default as ProcessingTest } from './ProcessingTest/ProcessingTest'
export { default as Snake } from './ProcessingTest/Snake/Snake'
export { default as FractalTree } from './ProcessingTest/FractalTree/FractalTree'
