export { default as NavigationBar } from './NavigationBar'
export { default as Home} from './home/home'
export { default as WhatsAppAnalyzer} from './whatsappAnalyzer/WhatsAppAnalyzer'
export { default as Snake } from './Snake/Snake'
export { default as FractalTree } from './FractalTree/FractalTree'
